import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react';

import Button from '../../components/Button';
import DriverCard from '../../components/DriverCard';
import TextInput from '../../components/TextInput';
import useUsers from '../../hooks/useUsers';
import useUsersQuery from '../../hooks/useUsersQuery';
import { SetSearchInput } from './DriverManagement.component.types';

const _onInputSearch = (setSearchInput: SetSearchInput)=>(event: React.ChangeEvent<HTMLInputElement>)=>{
  setSearchInput(event.target.value)
}

const DriverManagement: NextPage = (props) => {
  const {users:initialValue} = useUsersQuery();
  const [searchInput, setSearchInput]= useState<string>();
  const {users} = useUsers({initialValue, searchInput})

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>driver management page</p>
      <TextInput
        placeholder='Cari Driver'
        onChange={_onInputSearch(setSearchInput)}
        type='text'
      />
      <Button>
        Tambah Driver
      </Button>
      <br/>
      <Button>
        Prev Page
      </Button>
      <Button>
        Next Page
      </Button>
      {users.map(user=>(<DriverCard user={user}/>))}
    </div>
  )
}

export default DriverManagement
